api_platform:
    title: Meiridane
    version: 1.0.0
    enable_docs: true
    use_symfony_listeners: true
    mercure:
        enabled: true
        hub_url: '%env(string:MERCURE_PUBLIC_URL)%'
    patch_formats:
        json: [ "application/merge-patch+json" ]
        jsonapi: [ "application/vnd.api+json" ]
    formats:
        jsonld: [ 'application/ld+json' ]
        multipart: [ 'multipart/form-data' ]
    docs_formats:
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        extra_properties:
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 100
        collection:
            pagination:
                items_per_page_parameter_name: itemsPerPage
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header


